<?php

namespace Database\Seeders;

use App\Models\Service;
use App\Models\ServiceStep;
use Illuminate\Database\Seeder;

class ServiceStepSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            'new-passport' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Counter No. 1',
                    'counter_number' => 'Main Entrance Gate',
                    'title_en' => 'Token Gate & Form Pre-check',
                    'title_np' => 'टोकन गेट तथा फारम रुजु',
                    'instructions_en' => 'Verify online application printout, original Nepali citizenship certificate and NID number printout.',
                    'instructions_np' => 'अनलाइन आवेदन फारमको प्रिन्ट, नागरिकताको प्रमाणपत्र र राष्ट्रिय परिचयपत्र नम्बर रुजु गराउनुहोस्।',
                    'requirements_en' => ['Online application form printout', 'Original Nepali citizenship certificate', 'National Identity Number printout'],
                    'requirements_ne' => ['अनलाइन आवेदन फारम प्रिन्ट', 'नागरिकताको सक्कल प्रमाणपत्र', 'राष्ट्रिय परिचयपत्र नम्बर प्रिन्ट'],
                ],
                [
                    'step_number' => 2,
                    'room_number' => 'Room No. 102',
                    'counter_number' => 'First Floor',
                    'title_en' => 'Biometrics & Photography',
                    'title_np' => 'बायोमेट्रिक्स तथा फोटो',
                    'instructions_en' => 'Capture digital passport photo, fingerprints and digital signature.',
                    'instructions_np' => 'डिजिटल फोटो, औंठाछाप र डिजिटल दस्तखत रेकर्ड गराउनुहोस्।',
                    'requirements_en' => ['Token card', 'Checked application file'],
                    'requirements_ne' => ['टोकन कार्ड', 'रुजु भएको आवेदन फाइल'],
                ],
                [
                    'step_number' => 3,
                    'room_number' => 'Counter A-3',
                    'counter_number' => 'West Wing',
                    'title_en' => 'Original Document Verification',
                    'title_np' => 'सक्कल कागजात प्रमाणीकरण',
                    'instructions_en' => 'Officer verifies citizenship, NID and biometric slip before final approval.',
                    'instructions_np' => 'अधिकृतले नागरिकता, राष्ट्रिय परिचयपत्र र बायोमेट्रिक स्लिप भिडाएर अन्तिम स्वीकृति दिनुहुन्छ।',
                    'requirements_en' => ['Original citizenship certificate', 'Biometric confirmation slip'],
                    'requirements_ne' => ['सक्कल नागरिकता प्रमाणपत्र', 'बायोमेट्रिक स्लिप'],
                ],
                [
                    'step_number' => 4,
                    'room_number' => 'Counter No. 14',
                    'counter_number' => 'Collection Window',
                    'title_en' => 'Final Receipt & Collection Date',
                    'title_np' => 'अन्तिम रसिद तथा संकलन मिति',
                    'instructions_en' => 'Confirm final records and collect the passport collection-date slip.',
                    'instructions_np' => 'प्रणालीमा अन्तिम विवरण मिलान गरी राहदानी संकलन गर्ने मिति सहितको रसिद लिनुहोस्।',
                    'requirements_en' => ['Bank voucher / ConnectIPS receipt', 'Officer-approved dossier'],
                    'requirements_ne' => ['बैंक भौचर / कनेक्ट आईपीएस रसिद', 'अधिकृत स्वीकृत फाइल'],
                ]
            ],
            'passport-renewal' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Counter No. 4',
                    'counter_number' => 'Central Hall',
                    'title_en' => 'Previous Passport Check',
                    'title_np' => 'पुरानो राहदानी जाँच',
                    'instructions_en' => 'Verify old passport, bio-page copy and NID copy.',
                    'instructions_np' => 'पुरानो राहदानी, विवरण पाना र राष्ट्रिय परिचयपत्र प्रतिलिपि रुजु गराउनुहोस्।',
                    'requirements_en' => ['Old/damaged passport', 'Passport bio-page photocopy', 'NID copy'],
                    'requirements_ne' => ['पुरानो/बिग्रिएको राहदानी', 'राहदानी विवरण पानाको प्रतिलिपि', 'राष्ट्रिय परिचयपत्र प्रतिलिपि'],
                ],
                [
                    'step_number' => 2,
                    'room_number' => 'Room No. 105',
                    'counter_number' => 'First Floor',
                    'title_en' => 'Biometrics Update',
                    'title_np' => 'बायोमेट्रिक्स अद्यावधिक',
                    'instructions_en' => 'Update new photo, fingerprints and signature.',
                    'instructions_np' => 'नयाँ फोटो, औंठाछाप र दस्तखत अद्यावधिक गराउनुहोस्।',
                    'requirements_en' => ['Token card', 'Verification slip'],
                    'requirements_ne' => ['टोकन कार्ड', 'रुजु भौचर'],
                ],
                [
                    'step_number' => 3,
                    'room_number' => 'Counter No. 9',
                    'counter_number' => 'East Wing',
                    'title_en' => 'Receipt & Collection Date',
                    'title_np' => 'रसिद तथा संकलन मिति',
                    'instructions_en' => 'Confirm renewal approval and collect the barcoded collection slip.',
                    'instructions_np' => 'नवीकरण स्वीकृत गराई संकलन मिति सहितको बारकोड रसिद लिनुहोस्।',
                    'requirements_en' => ['Biometric slip', 'Old passport for cancellation'],
                    'requirements_ne' => ['बायोमेट्रिक भौचर', 'रद्द गर्न पुरानो राहदानी'],
                ]
            ],
            'urgent-passport' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Counter No. 11',
                    'counter_number' => 'Priority Desk',
                    'title_en' => 'Priority Screening Desk',
                    'title_np' => 'विशेष प्राथमिकता जाँच',
                    'instructions_en' => 'Verify fast-track payment and urgency justification documents.',
                    'instructions_np' => 'द्रुत सेवा शुल्क र अत्यावश्यकता प्रमाणित गर्ने कागजात रुजु गराउनुहोस्।',
                    'requirements_en' => ['Fast-track voucher', 'Urgency justification document', 'Original citizenship'],
                    'requirements_ne' => ['द्रुत सेवा भौचर', 'अत्यावश्यकताको प्रमाण', 'सक्कल नागरिकता'],
                ],
                [
                    'step_number' => 2,
                    'room_number' => 'Express Booth 7A',
                    'counter_number' => 'Ground Floor',
                    'title_en' => 'Express Biometrics',
                    'title_np' => 'एक्सप्रेस बायोमेट्रिक्स',
                    'instructions_en' => 'Use the priority queue to capture photo, fingerprint and signature.',
                    'instructions_np' => 'द्रुत लाइनबाट फोटो, औंठाछाप र दस्तखत रेकर्ड गराउनुहोस्।',
                    'requirements_en' => ['Priority token'],
                    'requirements_ne' => ['प्राथमिकता टोकन'],
                ],
                [
                    'step_number' => 3,
                    'room_number' => 'Counter No. 12',
                    'counter_number' => 'Express Dispatch Hub',
                    'title_en' => 'Final Approval & Dispatch Slip',
                    'title_np' => 'अन्तिम स्वीकृति तथा रसिद',
                    'instructions_en' => 'After officer approval, collect same-day/next-day dispatch slip.',
                    'instructions_np' => 'अधिकृत स्वीकृति पछि सोही दिन वा अर्को दिन संकलन मिति सहितको रसिद लिनुहोस्।',
                    'requirements_en' => ['Fast-track approved dossier'],
                    'requirements_ne' => ['द्रुत प्रक्रिया स्वीकृत फाइल'],
                ]
            ],
            'new-citizenship' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Counter No. 2',
                    'counter_number' => 'General Branch',
                    'title_en' => 'Application Form & Recommendation',
                    'title_np' => 'स्थानीय वडा सिफारिस तथा फारम दर्ता',
                    'instructions_en' => 'Submit ward recommendation letter, birth certificate and photos.',
                    'instructions_np' => 'वडाको सिफारिस पत्र, जन्म दर्ता र फोटो बुझाउनुहोस्।',
                    'requirements_en' => ['Ward recommendation', 'Birth registration', '3 Passport-size photos'],
                    'requirements_ne' => ['वडाको सिफारिस', 'जन्म दर्ता प्रमाणपत्र', '३ प्रति पासपोर्ट साइज फोटो'],
                ],
                [
                    'step_number' => 2,
                    'room_number' => 'Room No. 15',
                    'counter_number' => 'Administrative Officer',
                    'title_en' => 'Officer Interview & Witness Verification',
                    'title_np' => 'सनाखत तथा अधिकृत जाँच',
                    'instructions_en' => 'Witness must authenticate relationship status.',
                    'instructions_np' => 'सनाखत गर्ने संरक्षक (आमा/बुबा/नजिकको नातेदार) को उपस्थितिमा सनाखत गराउनुहोस्।',
                    'requirements_en' => ['Parent citizenship certificate', 'Relationship verification document'],
                    'requirements_ne' => ['आमा/बुबाको नागरिकता', 'नाता प्रमाणित प्रमाणपत्र'],
                ],
                [
                    'step_number' => 3,
                    'room_number' => 'Counter No. 5',
                    'counter_number' => 'Citizenship Window',
                    'title_en' => 'Citizenship Issuance & Registering',
                    'title_np' => 'नागरिकता वितरण तथा दर्ता',
                    'instructions_en' => 'Get citizenship certificate signed by Assistant Chief District Officer.',
                    'instructions_np' => 'सहायक प्रमुख जिल्ला अधिकारीबाट स्वीकृत नागरिकताको प्रमाणपत्र बुझिलिनुहोस्।',
                    'requirements_en' => ['Verified application file'],
                    'requirements_ne' => ['रुजु भएको आवेदन फाइल'],
                ]
            ],
            'general-inquiry' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Front Desk',
                    'counter_number' => 'Inquiry Desk',
                    'title_en' => 'Front Desk Support',
                    'title_np' => 'सोधपुछ कक्ष सहायता',
                    'instructions_en' => 'Ask for general guidance and help sheets.',
                    'instructions_np' => 'कार्यालयको काम सम्बन्धी जानकारी र फारमहरू लिनुहोस्।',
                    'requirements_en' => ['None'],
                    'requirements_ne' => ['कुनै पनि छैन'],
                ]
            ],
            'new-nid' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Counter No. 7',
                    'counter_number' => 'National ID Wing',
                    'title_en' => 'Verification & Pre-enrollment Check',
                    'title_np' => 'प्रारम्भिक रुजु तथा दर्ता जाँच',
                    'instructions_en' => 'Check pre-enrollment form barcode.',
                    'instructions_np' => 'अनलाइन भरेको प्रि-एनरोलमेन्ट फारम र बारकोड रुजु गराउनुहोस्।',
                    'requirements_en' => ['Pre-enrollment receipt', 'Original Nepali citizenship'],
                    'requirements_ne' => ['प्रि-एनरोलमेन्ट रसिद', 'सक्कल नागरिकता प्रमाणपत्र'],
                ],
                [
                    'step_number' => 2,
                    'room_number' => 'Room No. 104',
                    'counter_number' => 'Biometric Suite',
                    'title_en' => 'Biometric Enrollment Desk',
                    'title_np' => 'बायोमेट्रिक विवरण कक्ष',
                    'instructions_en' => 'Complete fingerprint, photo, and iris scan.',
                    'instructions_np' => 'औंठाछाप, फोटो र आँखाको नानीको जैविक विवरण दर्ता गराउनुहोस्।',
                    'requirements_en' => ['Verified barcode slip'],
                    'requirements_ne' => ['रुजु गरिएको बारकोड पाना'],
                ]
            ],

            'police-clearance-certificate' => [
    [
        'step_number' => 1,
        'room_number' => 'Online Portal',
        'counter_number' => 'Police Clearance System',
        'title_en' => 'Online Application Submission',
        'title_np' => 'अनलाइन आवेदन पेश गर्ने',
        'instructions_en' => 'Create or login to your account, fill personal details, address, purpose and passport/citizenship details.',
        'instructions_np' => 'खाता खोल्नुहोस् वा लगइन गरी व्यक्तिगत विवरण, ठेगाना, प्रयोजन र राहदानी/नागरिकता विवरण भर्नुहोस्।',
        'requirements_en' => ['Valid mobile number', 'Email address', 'Citizenship or passport details'],
        'requirements_ne' => ['मान्य मोबाइल नम्बर', 'इमेल ठेगाना', 'नागरिकता वा राहदानी विवरण'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Verification Desk',
        'counter_number' => 'Record Verification',
        'title_en' => 'Document and Record Verification',
        'title_np' => 'कागजात तथा अभिलेख रुजु',
        'instructions_en' => 'Police verifies submitted identity documents and checks criminal record status.',
        'instructions_np' => 'प्रहरीले पेश गरिएका परिचय कागजात र आपराधिक अभिलेख स्थिति रुजु गर्छ।',
        'requirements_en' => ['Uploaded documents', 'Application reference number'],
        'requirements_ne' => ['अपलोड गरिएका कागजात', 'आवेदन सन्दर्भ नम्बर'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Online Portal',
        'counter_number' => 'Certificate Download',
        'title_en' => 'Certificate Download',
        'title_np' => 'प्रमाणपत्र डाउनलोड',
        'instructions_en' => 'After approval, login and download the police clearance certificate.',
        'instructions_np' => 'स्वीकृत भएपछि लगइन गरी प्रहरी चारित्रिक प्रमाणपत्र डाउनलोड गर्नुहोस्।',
        'requirements_en' => ['Approved application', 'Login credentials'],
        'requirements_ne' => ['स्वीकृत आवेदन', 'लगइन विवरण'],
    ],
],

'lost-document-report' => [
    [
        'step_number' => 1,
        'room_number' => 'Online Portal',
        'counter_number' => 'Lost Document System',
        'title_en' => 'Lost Document Details Entry',
        'title_np' => 'हराएको कागजात विवरण प्रविष्टि',
        'instructions_en' => 'Select document type and enter document number, issued office, lost place and lost date if available.',
        'instructions_np' => 'कागजात प्रकार छानी नम्बर, जारी कार्यालय, हराएको स्थान र मिति उपलब्ध भए भर्नुहोस्।',
        'requirements_en' => ['Document type', 'Document number if available', 'Applicant contact details'],
        'requirements_ne' => ['कागजात प्रकार', 'उपलब्ध भए कागजात नम्बर', 'निवेदकको सम्पर्क विवरण'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Verification Desk',
        'counter_number' => 'Document Check',
        'title_en' => 'Identity Verification',
        'title_np' => 'परिचय रुजु',
        'instructions_en' => 'Verify applicant identity and lost document information.',
        'instructions_np' => 'निवेदकको परिचय र हराएको कागजातको विवरण रुजु गरिन्छ।',
        'requirements_en' => ['Citizenship or valid ID copy', 'Application reference number'],
        'requirements_ne' => ['नागरिकता वा मान्य परिचयपत्र प्रतिलिपि', 'आवेदन सन्दर्भ नम्बर'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Online Portal',
        'counter_number' => 'Report Print',
        'title_en' => 'Report Download or Print',
        'title_np' => 'प्रतिवेदन डाउनलोड वा प्रिन्ट',
        'instructions_en' => 'Download or print the lost document report after approval.',
        'instructions_np' => 'स्वीकृत भएपछि हराएको कागजात प्रतिवेदन डाउनलोड वा प्रिन्ट गर्नुहोस्।',
        'requirements_en' => ['Approved report', 'Application ID'],
        'requirements_ne' => ['स्वीकृत प्रतिवेदन', 'आवेदन आईडी'],
    ],
],

'cyber-crime-complaint' => [
    [
        'step_number' => 1,
        'room_number' => 'Applicant Side',
        'counter_number' => 'Evidence Preparation',
        'title_en' => 'Prepare Cyber Evidence',
        'title_np' => 'साइबर प्रमाण तयारी',
        'instructions_en' => 'Collect screenshots, links, messages, account details, transaction proof and other evidence before filing.',
        'instructions_np' => 'उजुरी दिनु अघि स्क्रीनसट, लिंक, म्यासेज, खाता विवरण, कारोबार प्रमाण र अन्य प्रमाण संकलन गर्नुहोस्।',
        'requirements_en' => ['Screenshots', 'Links or URLs', 'Transaction proof if related to fraud'],
        'requirements_ne' => ['स्क्रीनसट', 'लिंक वा URL', 'ठगी सम्बन्धी भए कारोबार प्रमाण'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Cyber Bureau / Police Office',
        'counter_number' => 'Complaint Registration',
        'title_en' => 'Complaint Submission',
        'title_np' => 'उजुरी दर्ता',
        'instructions_en' => 'Submit written complaint with identity document and available digital evidence.',
        'instructions_np' => 'परिचय कागजात र उपलब्ध डिजिटल प्रमाण सहित लिखित उजुरी पेश गर्नुहोस्।',
        'requirements_en' => ['Written complaint', 'Citizenship or valid ID copy', 'Evidence files'],
        'requirements_ne' => ['लिखित उजुरी', 'नागरिकता वा मान्य परिचयपत्र प्रतिलिपि', 'प्रमाण फाइलहरू'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Investigation Unit',
        'counter_number' => 'Follow-up Desk',
        'title_en' => 'Investigation Follow-up',
        'title_np' => 'अनुसन्धान फलोअप',
        'instructions_en' => 'Keep complaint reference number and cooperate with police during investigation.',
        'instructions_np' => 'उजुरी सन्दर्भ नम्बर सुरक्षित राखी अनुसन्धानको क्रममा प्रहरीलाई सहयोग गर्नुहोस्।',
        'requirements_en' => ['Complaint reference number', 'Additional evidence if requested'],
        'requirements_ne' => ['उजुरी सन्दर्भ नम्बर', 'माग भए थप प्रमाण'],
    ],
],

'personal-pan-registration' => [
    [
        'step_number' => 1,
        'room_number' => 'Taxpayer Portal',
        'counter_number' => 'Online Registration',
        'title_en' => 'Online PAN Form Submission',
        'title_np' => 'अनलाइन PAN फारम पेश गर्ने',
        'instructions_en' => 'Fill personal details, address, occupation and contact information in taxpayer portal.',
        'instructions_np' => 'करदाता पोर्टलमा व्यक्तिगत विवरण, ठेगाना, पेशा र सम्पर्क विवरण भर्नुहोस्।',
        'requirements_en' => ['Citizenship details', 'Mobile number', 'Email address'],
        'requirements_ne' => ['नागरिकता विवरण', 'मोबाइल नम्बर', 'इमेल ठेगाना'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Concerned Tax Office',
        'counter_number' => 'PAN Verification Desk',
        'title_en' => 'Identity Verification',
        'title_np' => 'परिचय रुजु',
        'instructions_en' => 'Visit the selected tax office if physical verification is required.',
        'instructions_np' => 'भौतिक प्रमाणीकरण आवश्यक भए छानिएको कर कार्यालयमा जानुहोस्।',
        'requirements_en' => ['Original citizenship', 'Application submission number'],
        'requirements_ne' => ['सक्कल नागरिकता', 'आवेदन दर्ता नम्बर'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Tax Office / Portal',
        'counter_number' => 'PAN Certificate',
        'title_en' => 'PAN Certificate Collection',
        'title_np' => 'PAN प्रमाणपत्र प्राप्ति',
        'instructions_en' => 'Collect or download PAN certificate after approval.',
        'instructions_np' => 'स्वीकृत भएपछि PAN प्रमाणपत्र प्राप्त वा डाउनलोड गर्नुहोस्।',
        'requirements_en' => ['Approved PAN application'],
        'requirements_ne' => ['स्वीकृत PAN आवेदन'],
    ],
],

'business-pan-registration' => [
    [
        'step_number' => 1,
        'room_number' => 'Taxpayer Portal',
        'counter_number' => 'Business Registration',
        'title_en' => 'Business Taxpayer Form Submission',
        'title_np' => 'व्यवसायिक करदाता फारम पेश गर्ने',
        'instructions_en' => 'Enter business name, registration number, address, nature of business and owner/director details.',
        'instructions_np' => 'व्यवसायको नाम, दर्ता नम्बर, ठेगाना, व्यवसायको प्रकृति र सञ्चालक/प्रोप्राइटर विवरण भर्नुहोस्।',
        'requirements_en' => ['Business registration certificate', 'Owner/director citizenship details'],
        'requirements_ne' => ['व्यवसाय दर्ता प्रमाणपत्र', 'सञ्चालक/प्रोप्राइटरको नागरिकता विवरण'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Concerned Tax Office',
        'counter_number' => 'Business Verification Desk',
        'title_en' => 'Document Verification',
        'title_np' => 'कागजात रुजु',
        'instructions_en' => 'Tax office verifies business registration, owner identity and business location documents.',
        'instructions_np' => 'कर कार्यालयले व्यवसाय दर्ता, सञ्चालकको परिचय र व्यवसाय स्थानका कागजात रुजु गर्छ।',
        'requirements_en' => ['Original business registration', 'Rental agreement or ownership proof'],
        'requirements_ne' => ['सक्कल व्यवसाय दर्ता', 'भाडा सम्झौता वा स्वामित्व प्रमाण'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Tax Office',
        'counter_number' => 'PAN Certificate',
        'title_en' => 'Business PAN Certificate',
        'title_np' => 'व्यवसायिक PAN प्रमाणपत्र',
        'instructions_en' => 'Receive business PAN certificate after approval.',
        'instructions_np' => 'स्वीकृत भएपछि व्यवसायिक PAN प्रमाणपत्र प्राप्त गर्नुहोस्।',
        'requirements_en' => ['Approved business taxpayer application'],
        'requirements_ne' => ['स्वीकृत व्यवसायिक करदाता आवेदन'],
    ],
],

'vat-registration' => [
    [
        'step_number' => 1,
        'room_number' => 'Taxpayer Portal',
        'counter_number' => 'Tax Type Update',
        'title_en' => 'VAT Registration Request',
        'title_np' => 'VAT दर्ता अनुरोध',
        'instructions_en' => 'Login to taxpayer portal and request VAT registration or tax type update.',
        'instructions_np' => 'करदाता पोर्टलमा लगइन गरी VAT दर्ता वा कर प्रकार अद्यावधिक अनुरोध गर्नुहोस्।',
        'requirements_en' => ['Business PAN', 'Taxpayer login'],
        'requirements_ne' => ['व्यवसायिक PAN', 'करदाता लगइन'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Concerned Tax Office',
        'counter_number' => 'VAT Verification Desk',
        'title_en' => 'Turnover and Business Verification',
        'title_np' => 'कारोबार तथा व्यवसाय रुजु',
        'instructions_en' => 'Submit business transaction, turnover and location documents for verification.',
        'instructions_np' => 'व्यवसायिक कारोबार, टर्नओभर र व्यवसाय स्थानका कागजात प्रमाणीकरणका लागि पेश गर्नुहोस्।',
        'requirements_en' => ['Business registration', 'Turnover details', 'Rental agreement or ownership proof'],
        'requirements_ne' => ['व्यवसाय दर्ता', 'टर्नओभर विवरण', 'भाडा सम्झौता वा स्वामित्व प्रमाण'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Tax Office',
        'counter_number' => 'VAT Approval',
        'title_en' => 'VAT Approval',
        'title_np' => 'VAT स्वीकृति',
        'instructions_en' => 'Receive VAT registration approval after office verification.',
        'instructions_np' => 'कार्यालय प्रमाणीकरणपछि VAT दर्ता स्वीकृति प्राप्त गर्नुहोस्।',
        'requirements_en' => ['Verified application file'],
        'requirements_ne' => ['रुजु भएको आवेदन फाइल'],
    ],
],

'tax-clearance-certificate' => [
    [
        'step_number' => 1,
        'room_number' => 'Taxpayer Portal',
        'counter_number' => 'Return Filing',
        'title_en' => 'Clear Pending Returns and Dues',
        'title_np' => 'बाँकी विवरण र कर चुक्ता',
        'instructions_en' => 'File pending returns and pay applicable tax dues before applying for clearance.',
        'instructions_np' => 'कर चुक्ता प्रमाणपत्र माग्नु अघि बाँकी विवरण पेश गरी तिर्नुपर्ने कर भुक्तानी गर्नुहोस्।',
        'requirements_en' => ['Tax returns', 'Tax payment vouchers'],
        'requirements_ne' => ['कर विवरण', 'कर भुक्तानी भौचर'],
    ],
    [
        'step_number' => 2,
        'room_number' => 'Taxpayer Portal / Tax Office',
        'counter_number' => 'Clearance Application',
        'title_en' => 'Tax Clearance Application',
        'title_np' => 'कर चुक्ता प्रमाणपत्र आवेदन',
        'instructions_en' => 'Apply for tax clearance certificate by selecting PAN and fiscal year.',
        'instructions_np' => 'PAN र आर्थिक वर्ष छानी कर चुक्ता प्रमाणपत्रका लागि आवेदन दिनुहोस्।',
        'requirements_en' => ['PAN number', 'Fiscal year details'],
        'requirements_ne' => ['PAN नम्बर', 'आर्थिक वर्ष विवरण'],
    ],
    [
        'step_number' => 3,
        'room_number' => 'Concerned Tax Office',
        'counter_number' => 'Verification and Certificate',
        'title_en' => 'Verification and Certificate Issue',
        'title_np' => 'रुजु तथा प्रमाणपत्र जारी',
        'instructions_en' => 'Tax office verifies payment records and issues tax clearance certificate.',
        'instructions_np' => 'कर कार्यालयले भुक्तानी अभिलेख रुजु गरी कर चुक्ता प्रमाणपत्र जारी गर्छ।',
        'requirements_en' => ['Verified tax record', 'Approved application'],
        'requirements_ne' => ['रुजु भएको कर अभिलेख', 'स्वीकृत आवेदन'],
    ],
],
            'new-license' => [
                [
                    'step_number' => 1,
                    'room_number' => 'Medical Branch',
                    'counter_number' => 'Ground Floor',
                    'title_en' => 'Medical Fitness Desk',
                    'title_np' => 'स्वास्थ्य तथा निरोगिता जाँच',
                    'instructions_en' => 'Submit blood group report and visual check sheet.',
                    'instructions_np' => 'रक्त समूह र आँखा परीक्षण रिपोर्ट प्रमाणित गराउनुहोस्।',
                    'requirements_en' => ['Medical fitness slip', 'Original citizenship certificate'],
                    'requirements_ne' => ['निरोगिताको प्रमाणपत्र', 'सक्कल नागरिकता प्रमाणपत्र'],
                ],
                [
                    'step_number' => 2,
                    'room_number' => 'Exam Hall',
                    'counter_number' => 'Second Floor',
                    'title_en' => 'Written Examination',
                    'title_np' => 'लिखित परीक्षा कक्ष',
                    'instructions_en' => 'Complete the written license exam sheet.',
                    'instructions_np' => 'सवारी चालक अनुमति पत्रको लिखित परीक्षा उत्तीर्ण गर्नुहोस्।',
                    'requirements_en' => ['Exam admit card'],
                    'requirements_ne' => ['परीक्षा प्रवेश पत्र'],
                ]
            ]
        ];

        foreach ($services as $serviceSlug => $steps) {
            $service = Service::where('slug', $serviceSlug)->first();
            if ($service) {
                foreach ($steps as $step) {
                    ServiceStep::updateOrCreate(
                        [
                            'service_id' => $service->id,
                            'step_number' => $step['step_number']
                        ],
                        [
                            'room_number' => $step['room_number'],
                            'counter_number' => $step['counter_number'],
                            'title_en' => $step['title_en'],
                            'title_np' => $step['title_np'],
                            'instructions_en' => $step['instructions_en'],
                            'instructions_np' => $step['instructions_np'],
                            'requirements_en' => $step['requirements_en'],
                            'requirements_ne' => $step['requirements_ne']
                        ]
                    );
                }
            }
        }
    }
}